entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      tls:
        certResolver: devResolver 
        domains:
          - main: "{{env MAIN_DOMAIN}}"
            sans:
              - "*.{{env MAIN_DOMAIN}}"

log:
  filePath: "/logs/log.json"
  format: json

accessLog:
  filePath: "/logs/accessLog.json"
  format: json

providers:
  docker:
    endpoint: "unix://var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  devResolver:
    acme:
      email: "{{env ACME_EMAIL}}"
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
      dnsChallenge:
        provider: godaddy
        delayBeforeCheck: 0